### ISSUE TITLE
C# request

### ISSUE THREAD

**Issue by JuliusJacobsohn** [Tewki/CSGO-Item-Floats-From-Inspect-Links#1]
First of all, thanks for providing this, it already helped a great deal. However, I still can't get this to work. It sounds so simple on paper, send some request to some server and get a response :[

I don't want to appear lazy, however I must say I haven't bothered much with protobuf. I wrote several steambot implementations (jessecars C# bot as base) and never had big problems, but this is seriously bothering me.

The problem is that I don't know how to convert this (the sample code you linked):
> var payload = new protos.CMsgGCCStrike15_v2_MatchListRequestLiveGameForUser({
>     accountid: accountid
>   });
>   this._gc.send({msg:CSGO.ECSGOCMsg.k_EMsgGCCStrike15_v2_MatchListRequestLiveGameForUser , proto: {}},
> payload.toBuffer(), callback);

to C#, and what's worse, I have no idea where to learn it (without learning every detail about protobuf and steamkit)

I'd be really thankful if you could add a C# example to your tutorial just to show which classes to use to send and receive requests. The SteamGameCoordinator exists in C#, but the send method has a different signature and all of this is a little too much for my 2 AM brain.

Cheers

**Comment by shaunidiot** [comment]
Have you tried using [SteamKit](https://github.com/SteamRE/SteamKit)?

**Comment by JuliusJacobsohn** [comment]
Yes. Like I said, I'm not sure which classes/methods to use as some signatures vary in a way I can't comprehend

**Comment by Tewki** [comment]
Don't know if this will help since I don't exactly understand your question myself as I've been up and running for the past few days,
But wrote a small bot via teamviewer a good while back to show him how to send 
https://gist.github.com/Tewki/213c952f40143e3db668

Contains a lot of shit doe since he asked multiple questions

**Comment by JuliusJacobsohn** [comment]
Line #40+ was exactly what I needed, thanks a lot dude!
